### ISSUE TITLE
We need a README!

### ISSUE THREAD

**Issue by edwinvrgs** [gregsanz182/PyRus#1]
Sería chevere tener un readme con descripción, instrucciones de instalación, etc. Por si acaso alguien (también yo) quiere probar

**Comment by gregsanz182** [comment]
Hey @edwinvrgs. Thanks for your suggestion. This application is still in developement. Changes are being made every now and then, but the project is still in its very first stage. The repository will change to private till' I have something to show. Thanks again for the feedback.

--------------------
Hey @edwinvrgs. Gracias por tu sugerencia. Esta aplicación está aun en desarrollo. Se están realizando cambios cada cierto tiempo, pero está aun en su primera etapa de desarrollo. Cambiaré el repositorio a privado hasta que tenga algo que mostrar. Gracias nuevamente por la retroalimentacion.
